// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace gymlocator.Core.Shopping.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Item
    {
        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item(int id, System.DateTime added, System.DateTime done, string name, bool completed, int storeID, int listId, double lat, double lng, bool priceExists, double price, string barcode)
        {
            Id = id;
            Added = added;
            Done = done;
            Name = name;
            Completed = completed;
            StoreID = storeID;
            ListId = listId;
            Lat = lat;
            Lng = lng;
            PriceExists = priceExists;
            Price = price;
            Barcode = barcode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "added")]
        public System.DateTime Added { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "done")]
        public System.DateTime Done { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeID")]
        public int StoreID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listId")]
        public int ListId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lat")]
        public double Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lng")]
        public double Lng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "priceExists")]
        public bool PriceExists { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "barcode")]
        public string Barcode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Barcode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Barcode");
            }
        }
    }
}
