// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace gymlocator.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Details for getting in touch with the gym.
    /// </summary>
    public partial class ContactDetails
    {
        /// <summary>
        /// Initializes a new instance of the ContactDetails class.
        /// </summary>
        public ContactDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContactDetails class.
        /// </summary>
        /// <param name="email">E-mail address to the gym</param>
        /// <param name="phone">Phone number to the gym. Could be an
        /// international phone number.</param>
        public ContactDetails(string email = default(string), string phone = default(string))
        {
            Email = email;
            Phone = phone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets e-mail address to the gym
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets phone number to the gym. Could be an international
        /// phone number.
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

    }
}
